### ISSUE TITLE
Can you update the firmware release for the Arduino MKR Vidor?

### ISSUE THREAD

**Issue by mbanzi** [FPGAArcade/replay_release#3]
I'm testing on the Vidor but the binary version is a bit old :)

**Comment by erique** [comment]
We absolutely should!
The most recent build can be found here https://github.com/FPGAArcade/replay_firmware/suites/1657608872/artifacts/30803844
But please note - this one hasn't been verified working on the actual board. (just in case you want to try it out)

**Comment by erique** [comment]
Uploaded the most recent build (7595326).
