### ISSUE TITLE
Compiling example on Arduino VIDOR 4000 fails

### ISSUE THREAD

**Issue by mbanzi** [FPGAArcade/replay_release#5]
thanks for providing a new binary for the VIDOR.
I tried to compile the example "Replay_Boot"
this is what I get

`Library replay_mkrvidor4000 has been declared precompiled:
Using precompiled library in /Users/bluemax/Documents/Arduino/libraries/replay_mkrvidor4000/src/cortex-m0plus
/Users/bluemax/Documents/Arduino/libraries/replay_mkrvidor4000/src/cortex-m0plus/libreplay.a(vidor.o): In function 'vidor_SPI_beginTransaction(unsigned char)':
(.text._ZL26vidor_SPI_beginTransactionh+0x16): undefined reference to 'SPIClass::beginTransaction(SPISettings)'
/Users/bluemax/Documents/Arduino/libraries/replay_mkrvidor4000/src/cortex-m0plus/libreplay.a(vidor.o): In function 'vidor_SPI_endTransaction(unsigned char)':
(.text._ZL24vidor_SPI_endTransactionh+0x16): undefined reference to 'SPIClass::endTransaction()'
/Users/bluemax/Documents/Arduino/libraries/replay_mkrvidor4000/src/cortex-m0plus/libreplay.a(vidor.o): In function 'SPI_Init':
(.text.SPI_Init+0x44): undefined reference to 'SPIClass::begin()'
/Users/bluemax/Documents/Arduino/libraries/replay_mkrvidor4000/src/cortex-m0plus/libreplay.a(vidor.o): In function 'rSPI':
(.text.rSPI+0x6): undefined reference to 'SPIClass::transfer(unsigned char)'
/Users/bluemax/Documents/Arduino/libraries/replay_mkrvidor4000/src/cortex-m0plus/libreplay.a(vidor.o): In function 'JTAG_Init':
(.text.JTAG_Init+0x4a): undefined reference to 'SPIClass::begin()'
(.text.JTAG_Init+0x54): undefined reference to 'SPIClass::beginTransaction(SPISettings)'
/Users/bluemax/Documents/Arduino/libraries/replay_mkrvidor4000/src/cortex-m0plus/libreplay.a(vidor.o): In function 'FPGA_WriteBitstream':
(.text.FPGA_WriteBitstream+0x58): undefined reference to 'SPIClass::transfer(unsigned char)'
collect2: error: ld returned 1 exit status
exit status 1
Error compiling for board Arduino MKR Vidor 4000.`

any clue?

**Comment by erique** [comment]
@mbanzi New build uploaded (627f573)

**Comment by mbanzi** [comment]
thanks for diagnosing the problem so quickly, I'll test it today
